interface Request {
    _id: string,
    title: string,
    address: string,
    description: string,
    author: User,
    section: number,
    category: number,
    status: boolean,
    disabled: boolean,
    approved: boolean,
    top: boolean,
    time_range: null | TimeRange,
    views: number,
    comments: Comment[],
    closed_at: string,
    created_at: string,
    updated_at: string,
}